#### Задание 1

In [ ]:
import numpy as np

In [12]:
# Создаем массив 5x2

a = np.array([[1, 6],
              [2, 8], 
              [3, 10], 
              [3, 11], 
              [1, 7]])

In [13]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 10],
       [ 3, 11],
       [ 1,  7]])

In [20]:
#  Находим среднее значение

np.mean(a, axis = 0)

array([2. , 8.4])

In [22]:
mean_a = np.mean(a, axis = 0)

In [23]:
mean_a

array([2. , 8.4])

#### Задание 2

In [24]:
# Получение нового массива в результате вычитания двух других

a_centered = a - mean_a

In [25]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  1.6],
       [ 1. ,  2.6],
       [-1. , -1.4]])

#### Задание 3

In [27]:
# Умножение массива на скаляр

a_centered_sp = a_centered * 2

In [28]:
a_centered_sp

array([[-2. , -4.8],
       [ 0. , -0.8],
       [ 2. ,  3.2],
       [ 2. ,  5.2],
       [-2. , -2.8]])

In [34]:
# Деление a_centered_sp на N-1 

c = a_centered_sp / (a.shape[0]-1)

In [35]:
c

array([[-0.5, -1.2],
       [ 0. , -0.2],
       [ 0.5,  0.8],
       [ 0.5,  1.3],
       [-0.5, -0.7]])

#### Задание 4

In [40]:
np.cov(a_centered_sp)[0,1]

1.1200000000000012

#### Задание 5

In [41]:
import pandas as pd

In [43]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                       'author_name':['Тургенев', 'Чехов', 'Островский']}, columns = ['author_id', 'author_name'])

In [44]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [45]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                       'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 
                                     'Гроза', 'Таланты и поклонники'],
                    'price':[450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id', 'book_title', 'price'])

In [46]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [48]:
authors.merge(book, how = 'left')

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [52]:
autors_price = authors.merge(book, how = 'left')

In [53]:
autors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [55]:
top5 = autors_price.nlargest(5, 'price')

* Создайте датафрейм authors_stat на основе информации из authors_price.
* В датафрейме authors_stat должны быть четыре столбца: author_name, min_price, max_price, mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [129]:
# Максимальная цена
max_price = autors_price.groupby('author_name', as_index = False)['price'].max()
max_price.rename(columns={'price': 'max_price'}, inplace = True)
max_price

author_name  max_price
0  Островский        370
1    Тургенев        450
2       Чехов        500

In [134]:
# Минимальная цена
min_price = autors_price.groupby('author_name', as_index = False)['price'].min()
min_price.rename(columns={'price': 'min_price', 'author_name': 'author_name_1'}, inplace = True)
min_price

author_name_1  min_price
0    Островский        290
1      Тургенев        300
2         Чехов        450

In [135]:
# Средняя цена
mean_price = autors_price.groupby('author_name', as_index = False)['price'].mean()
mean_price.rename(columns={'price': 'mean_price', 'author_name': 'author_name_2'}, inplace = True)
mean_price

author_name_2  mean_price
0    Островский  330.000000
1      Тургенев  366.666667
2         Чехов  475.000000

In [136]:
authors_stat = pd.concat([max_price, min_price, mean_price], axis = 1, ignore_index=False)
authors_stat 

author_name  max_price author_name_1  min_price author_name_2  mean_price
0  Островский        370    Островский        290    Островский  330.000000
1    Тургенев        450      Тургенев        300      Тургенев  366.666667
2       Чехов        500         Чехов        450         Чехов  475.000000

In [138]:
authors_stat = authors_stat.drop(authors_stat.columns[[2, 4]], axis = 'columns')
authors_stat

author_name  max_price  min_price  mean_price
0  Островский        370        290  330.000000
1    Тургенев        450        300  366.666667
2       Чехов        500        450  475.000000